config/routes.rb
ChapterMap::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  match '/users/auth/:provider/callback', to: 'users#omniauth_callbacks', via: [:get, :post]

                   
  resources :chapter_leaders


  resources :members do
    collection do post :import end
  end

  resources :chapters
  resources :attachments

  resources :chapters do
    collection do post :import end
  end

  resources :chapters do
    collection do post :delete_multiple end
  end

  
  resources :users

  resources :users do
    collection do post :delete_multiple end
  end
  resources :users do
    member do
      get :confirm
    end
  end


  get 'full' => 'home#full'
  get 'embed' => 'home#embed'
  get 'pflag' => 'home#pflag'
  get 'show_chapters' => 'home#show_chapters'
  get 'chapters/import' => 'chapters#import'
  get 'members/import' => 'members#import'

  get "/activate" => "users#confirm"

  root :to => "home#pflag"

end

app/models/chapter_leader.rb
# == Schema Information
#
# Table name: chapter_leaders
#
#  id                        :integer          not null, primary key
#  chapter_id                :integer
#  member_id                 :integer
#  position                  :string(255)
#  spouse_position           :string(255)
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  position_import_id        :string(255)
#  spouse_position_import_id :string(255)
#

class ChapterLeader < ActiveRecord::Base
#  attr_accessible :chapter_id, :leader_id, :position_1, :position_2, :position_3, :position_4, :position_5, :spouse_position_1, :spouse_position_2, :spouse_position_3, :spouse_position_4, :spouse_position_5
  belongs_to :chapter
  belongs_to :member

  def self.positions
  	["","Board Member","President","Vice President","Treasurer","Secretary","Executive Director","Co-President","Communications Coordinator","Diversity Coordinator","Advocacy Coordinator","Fundraising Coordinator","Membership Coordinator","Safe Schools Coordinator","Speakers Bureau Coordinator","State Coordinator","Transgender Coordinator","Programs Coordinator","Web Manager"]
  end
end

app/controllers/chapter_leaders_controller.rb
class ChapterLeadersController < ApplicationController
  load_and_authorize_resource
  # GET /chapter_leaders
  # GET /chapter_leaders.json
  def index
    @chapter_leaders = ChapterLeader.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chapter_leaders }
    end
  end

  # GET /chapter_leaders/1
  # GET /chapter_leaders/1.json
  def show
    @chapter_leader = ChapterLeader.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chapter_leader }
    end
  end

  # GET /chapter_leaders/new
  # GET /chapter_leaders/new.json
  def new
    @chapter_leader = ChapterLeader.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chapter_leader }
    end
  end

  # GET /chapter_leaders/1/edit
  def edit
    @chapter_leader = ChapterLeader.find(params[:id])
  end

  # POST /chapter_leaders
  # POST /chapter_leaders.json
  def create
    respond_to do |format|
      if @chapter_leader.save
        format.html { redirect_to @chapter_leader, notice: 'Chapter leader was successfully created.' }
        format.json { render json: @chapter_leader, status: :created, location: @chapter_leader }
      else
        format.html { render action: "new" }
        format.json { render json: @chapter_leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chapter_leaders/1
  # PUT /chapter_leaders/1.json
  def update
    respond_to do |format|
      if @chapter_leader.update_attributes(chapter_leader_params)
        format.html { redirect_to @chapter_leader, notice: 'Chapter leader was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chapter_leader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapter_leaders/1
  # DELETE /chapter_leaders/1.json
  def destroy
    @chapter_leader = ChapterLeader.find(params[:id])
    @chapter_leader.destroy

    respond_to do |format|
      format.html { redirect_to chapter_leaders_url }
      format.json { head :no_content }
    end
  end
  private
  def chapter_leader_params
    params.require(:chapter_leader).permit(:chapter_id, :member_id, :position, :spouse_position,:position_import_id,:spouse_position_import_id)
  end
end

app/helpers/chapter_leaders_helper.rb
module ChapterLeadersHelper
end

app/views/chapter_leaders/_form.html.erb
<%= simple_form_for(@chapter_leader) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :chapter, prompt: "Select a chapter...", collection: Chapter.all, as: :group, group_method: :state %>
    <%= f.association :member %>
    <%= f.input :position, collection: ChapterLeader.positions %>
    <%= f.input :spouse_position, collection: ChapterLeader.positions %>
    <% if admin_user? %>
    <%= f.input :position_import_id %>
    <%= f.input :spouse_position_import_id %>
    <% end %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/chapter_leaders/edit.html.erb
<h1>Editing chapter_leader</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Show', @chapter_leader, :class => "btn btn-default" %> <%= link_to 'Back', chapter_leaders_path, :class => "btn btn-default" %>

app/views/chapter_leaders/index.html.erb
<h1>Chapter Leaders</h1>
<table class="table table-striped">
  <tr>
    <th><%=tt "name" %></th>
    <th><%=tt "chapter" %></th>
    <th><%=tt "spouse" %></th>
    <th><%=tt "spouse_position" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chapter_leaders.each do |chapter_leader| %>
  <tr>
    <% chapter_leader_name = chapter_leader.member.name unless chapter_leader.member.blank? || chapter_leader.id %>
    <td><%= link_to chapter_leader_name, chapter_leader %></td>
    <td><%= chapter_leader.chapter_id %></td>
    <td><%= chapter_leader.position %></td>
    <td><%= chapter_leader.spouse_position %></td>
    <td><%= link_to 'Edit', edit_chapter_leader_path(chapter_leader) %></td>
    <td><%= link_to 'Destroy', chapter_leader, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chapter leader', new_chapter_leader_path, :class => "btn btn-primary" %>

app/views/chapter_leaders/new.html.erb
<h1>New Chapter Leader</h1>

<%= render 'form' %>
<br/>

<%= link_to 'Back', chapter_leaders_path, :class => "btn btn-default" %>

app/views/chapter_leaders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Chapter:</b>
  <%= @chapter_leader.chapter_id %>
</p>

<p>
  <b>Leader:</b>
  <%= @chapter_leader.member.name %>
</p>

<p>
  <b>Position:</b>
  <%= @chapter_leader.position %>
</p>

  <b>Spouse position:</b>
  <%= @chapter_leader.spouse_position %>
</p>


<br>
<%= link_to 'Edit', edit_chapter_leader_path(@chapter_leader), :class => "btn btn-default" %> 
<%= link_to 'Back', chapter_leaders_path, :class => "btn btn-default" %>