config/routes.rb
ChapterMap::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  match '/users/auth/:provider/callback', to: 'users#omniauth_callbacks', via: [:get, :post]

                   
  resources :chapter_leaders


  resources :members do
    collection do post :import end
  end

  resources :chapters
  resources :attachments

  resources :chapters do
    collection do post :import end
  end

  resources :chapters do
    collection do post :delete_multiple end
  end

  
  resources :users

  resources :users do
    collection do post :delete_multiple end
  end
  resources :users do
    member do
      get :confirm
    end
  end


  get 'full' => 'home#full'
  get 'embed' => 'home#embed'
  get 'pflag' => 'home#pflag'
  get 'show_chapters' => 'home#show_chapters'
  get 'chapters/import' => 'chapters#import'
  get 'members/import' => 'members#import'

  get "/activate" => "users#confirm"

  root :to => "home#pflag"

end

app/views/layouts/_messages.html.erb
	<div id="flash-message">
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) and !(msg == "null")%>
	    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> fade in">
	      <a class="close" data-dismiss="alert">&#215;</a>
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
	  <% end %>
	<% end %>
	</div>

app/views/layouts/_navigation.html.erb
<ul class="nav navbar-nav">
  <% if user_signed_in? %>
    <li>
      <%= link_to 'Chapter Listings', chapters_path %>
    </li>
    <li>
       <%= link_to "Chapter Files", attachments_path %>
     </li>
    <li>
      <%= link_to 'Chapter Leaders', chapter_leaders_path %>
    </li>

    <li>
      <%= link_to 'Members', members_path if can? :index, Member %>
    </li>

    <li>
      <%= link_to 'Heat Map', 'https://ec4ddfd036b016bbe4f2c67ea5947bf8db58a0fc.googledrive.com/host/0Byxf7_dzGKoEUUZPX3lKU2Mxa1E/chapter-search-heat-map.html' if admin_user? %>
    </li>

    <li>
      <%= link_to current_user.email, edit_user_registration_path %>
    </li>

    <li>
    <%= link_to("Logout", destroy_user_session_path, :method => :delete) %>
    </li>
    <li>
 
    </li>
  <% else %>
    <li>
    <%if not Rails.env.production?%>
    <%= link_to 'Login', new_user_session_path %>
    <% else %>
    <%= link_to 'Login', 'http://pflag.org/login' %>
    <%end%>
    </li>
  <% end %>
  <% if admin_user? %>
    <li>
      <%= link_to "Users", users_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chapter Map" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chapter Map" %>">
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Chapter Map", root_path, :class => 'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
          <%= render 'layouts/navigation' %>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
      <div class="row">
        <%= render 'layouts/messages' %>
      </div>
      <div class="row">
          <%= yield %>
      </div>
    </div> <!--! end of .container -->
  <%= yield :scripts %>
  </body>
</html>

app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chapter Map" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chapter Map" %>">
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script type="text/javascript">
      var print = <%=params[:print] || "null"%>;
    </script>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  <%= yield :scripts %>
  </body>
</html>

app/views/layouts/full.html.erb
<!DOCTYPE html>
<html lang="en" height="100%">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chapter Map" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chapter Map" %>">
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script type="text/javascript">
      var print = <%=params[:print] || "null"%>;
    </script>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <script type="text/javascript">
    $().ready(function() {
      $("#map").height(window.height)
      $("div.well").remove();
      $("#chapter-listings").remove();
    });
    </script>
  </head>
  <body class="<%= controller_name %> <%= action_name %>" height="100%">
              <%= yield %>
  <%= yield :scripts %>
  </body>
</html>

app/views/layouts/pflag.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chapter Map" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chapter Map" %>">
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>

    <style>
    	body.home.pflag div.row {
        margin: 0 auto;
    		width: 800px;
    		background-color: white;
        padding: 0 auto;
    	}
    	body.home.pflag div#main-content-yield {
    		padding: 15px;
    		width: 800px;
    	}

    	body.home.pflag div#main {
    		margin-top: -55px;

    	}

    	body.home.pflag footer {
    		width: 800px;
    		background-color: white;
    	}
    	body.home.pflag {
    		background-color: #482458;
    	}
      table#rainbow-navbar {
        width: 100%;
        height: 34px;
        background-color: #62006e;
        border-collapse: collapse;
        border: 0px;
        padding: 0px;
        border-spacing: 0px;
      }

      div.rainbowNavigationTop {
        height: 34px;
        padding: 9px 6px;
        cursor: pointer;
        margin: 0px;
        border: 0px;
        font-weight: bold;
        font-size: 14px;
        color: rgb(255, 255, 255);
        float: left;
        text-align: center;
      }

      body.home.pflag div.content {
        background-color: transparent;
      }
      .purpleBG {
        background-color: rgb(166, 0, 187);
      }
      .redBG {
        background-color: rgb(195, 40, 49);
      }
      .yellowBG {
        background-color: rgb(245, 216, 83);
      }
      .orangeBG {
        background-color: rgb(246, 119, 24);
      }
      #PC3907_ctl00 td {
        padding: 0px 3px 0px 2px;
      }
    </style>

  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">

    				<table border="0" cellpadding="0" cellspacing="0" style="width: 100%;">
    						<tbody>
    							<tr>
    								<td class="top_main_bar" style="background-color: rgb(153, 153, 204); height: 25px; background-position: initial initial; background-repeat: initial initial;">
    									&nbsp;</td>
    							</tr>
    						</tbody>
    				</table>

          </div>

           <div class="row">
            	<table border="0" cellpadding="0" cellspacing="0" id="rainbow-navbar">
      					<tbody>
      						<tr>
      							<td class="rainbowNavigationTop" style="width: 149px; margin: 0px; padding-left: 10px; color: rgb(255, 255, 255);">
      								<a href="http://community.pflag.org/page.aspx?pid=618" pid="618" style="text-decoration: none; color: rgb(255, 255, 255);" tab="0">Site Search</a></td>
      							<td width="*">
      								<div class="rainbowNavigationTop purpleBG">
      									<a href="#" style="text-decoration: none; color: rgb(255, 255, 255);">FIND A CHAPTER</a></div>
      								<div class="rainbowNavigationTop redBG">
                      <% if Rails.env.production? %>
                        <a href="http://pflag.org/login" style="text-decoration: none; color: rgb(255, 255, 255);">LOGIN</a></div>
                      <% else %>
                        <a href="/login" style="text-decoration: none; color: rgb(255, 255, 255);">LOGIN</a></div>
                      <% end %>
      								<div class="rainbowNavigationTop yellowBG" style="">
      									<a href="https://community.pflag.org/SSLPage.aspx?pid=453" style="text-decoration: none; color: rgb(255, 255, 255);">BECOME A MEMBER</a></div>
      								<div class="rainbowNavigationTop orangeBG">
      									<a href="https://community.pflag.org/donate" style="text-decoration: none; color: rgb(255, 255, 255);">DONATE</a></div>
      							</td>
      						</tr>
      					</tbody>
      				</table>


          </div>

           <div class="row">
            	<table border="0" cellpadding="0" cellspacing="0" style="width: 795px;">
    						<tbody>
    							<tr>
    								<td id="logo" style="width: 180px;">
    									<a href="http://community.pflag.org/page.aspx?pid=194" style="text-decoration: none;"><img alt="" src="http://community.pflag.org/view.image?Id=394" style="border: 0px none;"></a></td>
    								<td id="bannercopy" style="color: rgb(195, 40, 49); font-size: 18px; font-weight: bold; background-image: url(http://community.pflag.org/view.image?id=395); padding-top: 60px; padding-left: 100px; background-repeat: no-repeat no-repeat;">
    									Find&nbsp;a PFLAG Chapter</td>
    							</tr>
    						</tbody>
    					</table>

          </div>

          <div class="row" id="main-content-yield">
              <%= render 'layouts/messages' %>

            	<%= yield %>
  	      </div>

          <div class="row">
          	<table>
	          	<tbody>
      					<tr>
  		  					<td align="center" id="footer" style="color: rgb(102, 0, 102); font-size: 10px; line-height: 13px; height: auto; padding: 10px 150px; text-align: center;">
    								<table cellpadding="5" cellspacing="0" class="menu513" id="PC3907_ctl00" style="color: rgb(153, 153, 204); font-size: 11px; padding-bottom: 10px; margin: 0px auto; border-collapse: collapse; z-index: 1000;">
    									<tbody>
    										<tr>
    											<td class="menuItem513" id="PC3907_ctl00-menuItem000" style="color: rgb(72, 36, 88); text-decoration: underline; padding-bottom: 10px; cursor: pointer;" title="Contact Us">
    												<a href="https://community.pflag.org/sslpage.aspx?pid=259">Contact Us</a></td>
    											<td class="menuItem513" id="PC3907_ctl00-menuItem001" style="color: rgb(72, 36, 88); text-decoration: underline; padding-bottom: 10px; cursor: pointer;" title="About PFLAG">
    												<a href="https://community.pflag.org/about">About PFLAG</a></td>
    											<td class="menuItem513" id="PC3907_ctl00-menuItem002" style="color: rgb(72, 36, 88); text-decoration: underline; padding-bottom: 10px; cursor: pointer;" title="Find a Chapter">
    												<a href="#">Find a Chapter</a></td>
    											<td class="menuItem513" id="PC3907_ctl00-menuItem003" style="color: rgb(72, 36, 88); text-decoration: underline; padding-bottom: 10px; cursor: pointer;" title="Join PFLAG">
    												<a href="https://community.pflag.org/donate">Join PFLAG</a></td>
    											<td class="menuItem513" id="PC3907_ctl00-menuItem004" style="color: rgb(72, 36, 88); text-decoration: underline; padding-bottom: 10px; cursor: pointer;" title="Site Search">
    												<a href="https://community.pflag.org/sslpage.aspx?pid=618">Site Search</a></td>
    										</tr>
    									</tbody>
    								</table>
                                    <p style="margin-top: 4px; margin-bottom: 8px;">
                                       PFLAG and PFLAG PARENTS, FAMILIES AND FRIENDS OF LESBIANS AND GAYS are registered trademarks and service marks of PFLAG, Inc.<br>&copy; PFLAG, Inc.&nbsp;2015. All Rights Reserved.
                                    </p>
    							</td>
  	 					  </tr>
              </tbody>
            </table>
	      </div>

        <footer>
        </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>