config/routes.rb
ChapterMap::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "users/omniauth_callbacks" }, :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  devise_scope :user do
    delete "/logout" => "devise/sessions#destroy"
  end
  devise_scope :user do
    get "/login" => "devise/sessions#new"
  end

  match '/users/auth/:provider/callback', to: 'users#omniauth_callbacks', via: [:get, :post]

                   
  resources :chapter_leaders


  resources :members do
    collection do post :import end
  end

  resources :chapters
  resources :attachments

  resources :chapters do
    collection do post :import end
  end

  resources :chapters do
    collection do post :delete_multiple end
  end

  
  resources :users

  resources :users do
    collection do post :delete_multiple end
  end
  resources :users do
    member do
      get :confirm
    end
  end


  get 'full' => 'home#full'
  get 'embed' => 'home#embed'
  get 'pflag' => 'home#pflag'
  get 'show_chapters' => 'home#show_chapters'
  get 'chapters/import' => 'chapters#import'
  get 'members/import' => 'members#import'

  get "/activate" => "users#confirm"

  root :to => "home#pflag"

end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                      :integer          not null
#  contituent_id           :string(255)
#  first_name              :string(255)
#  last_name               :string(255)
#  chapter_code            :string(255)
#  spouse_first_name       :string(255)
#  spouse_last_name        :string(255)
#  address                 :string(255)
#  city                    :string(255)
#  state                   :string(255)
#  zip                     :string(255)
#  phone                   :string(255)
#  email                   :string(255)
#  address_import_id       :string(255)
#  phone_import_id         :string(255)
#  email_import_id         :string(255)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  suppress_from_directory :boolean
#  chapter_id              :integer
#  import_id               :string(255)
#

class Member < ActiveRecord::Base
#  attr_accessible :address, :address_2, :address_import_id, :chapter_code, :city, :contituent_id, :email, :email_import_id, :first_name, :last_name, :phone, :phone_import_id, :spouse_first_name, :spouse_last_name, :state, :zip, :suppress_from_directory, :chapter_leaders_attributes
  has_many :chapter_leaders
  has_many :chapters, through: :chapter_leaders
  has_many :users, through: :chapters
  accepts_nested_attributes_for :chapter_leaders, :allow_destroy => true

  def link_to_chapter
  	unless chapter_code.empty?
  		self.chapter = Chapter.find_by_chapter_legacy_identifier chapter_code
  	end
  	self.chapter
  end

  def name
    "#{first_name} #{last_name}"
  end

  def chapter
  	if chapter_id.nil?
  		@self.link_to_chapter
  		Chapter.find(chapter_id) unless chapter_id.empty?
  	else
  		Chapter.find(chapter_id)
  	end
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  load_and_authorize_resource
  # GET /members
  # GET /members.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  def create
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /members/1
  # PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update_attributes(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
  def member_params
    params.require(:member).permit(:address, :address_import_id, :chapter_code, :city, 
      :contituent_id, :email, :email_import_id, :first_name, :last_name, 
      :phone, :phone_import_id, :spouse_first_name, :spouse_last_name, 
      :state, :zip, :suppress_from_directory, :chapter_leaders_attributes, :import_id)
  end

end

app/views/members/_chapter_leaders.html.erb
    <%= f.fields_for :chapter_leaders do |cl| %>
      <div class="well">
        <%= cl.select :chapter_id, grouped_options_for_select(chapters_by_state_for_select, @member.chapter_id) %>
        <p>Positions</p>

        <%= cl.select :position, ChapterLeader.positions %>
        <p>Household Member Position:</p>
        <%= cl.select :spouse_position, ChapterLeader.positions %>
        <p>
          <%= cl.link_to_remove "Remove this position" %>
        </p>
      </div>

    <% end %>
    <p><%= f.link_to_add "Add a position", :chapter_leaders %></p>

app/views/members/_form.html.erb
<%= simple_nested_form_for(@member) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :contituent_id if admin_user? %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :chapter_code if admin_user?  %>

    <%= render "chapter_leaders", :f => f %>
    <%= f.input :spouse_first_name %>
    <%= f.input :spouse_last_name %>
    <%= f.input :address, :as => :text, :input_html => { :cols => 40, :rows => 3 } %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <% if has_role? :admin %>
    <%= f.input :import_id %>
    <%= f.input :address_import_id %>
    <%= f.input :phone_import_id %>
    <%= f.input :email_import_id %>
    <% end %>
    <%= f.input :suppress_from_directory %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/import.html.erb
<h2>Import Members</h2>

<%= form_tag import_members_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/members/index.html.erb
<h1>Members</h1>

<table class="table table-striped">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Spouse first name</th>
    <th>Spouse last name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= member.first_name %></td>
    <td><%= member.last_name %></td>
    <td><%= member.spouse_first_name %></td>
    <td><%= member.spouse_last_name %></td>
    <td><%= member.address %></td>
    <td><%= member.city %></td>
    <td><%= member.state %></td>
    <td><%= member.zip %></td>
    <td><%= member.phone %></td>
    <td><%= member.email %></td>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path, :class => "btn btn-primary" %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contituent:</b>
  <%= @member.contituent_id %>
</p>

<p>
  <b>First name:</b>
  <%= @member.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @member.last_name %>
</p>

<p>
  <b>Chapter code:</b>
  <%= @member.chapter_code %>
</p>

<p>
  <b>Spouse first name:</b>
  <%= @member.spouse_first_name %>
</p>

<p>
  <b>Spouse last name:</b>
  <%= @member.spouse_last_name %>
</p>

<p>
  <b>Address:</b>
  <%= @member.address %>
</p>

<p>
  <b>City:</b>
  <%= @member.city %>
</p>

<p>
  <b>State:</b>
  <%= @member.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @member.zip %>
</p>

<p>
  <b>Phone:</b>
  <%= @member.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @member.email %>
</p>

<p>
  <b>Address import:</b>
  <%= @member.address_import_id %>
</p>

<p>
  <b>Phone import:</b>
  <%= @member.phone_import_id %>
</p>

<p>
  <b>Email import:</b>
  <%= @member.email_import_id %>
</p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>